name: Python CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pre-commit:
    uses: darbiadev/.github/.github/workflows/generic-precommit.yaml@c4fb123ed14ed8cc9df9820ca63bace02981e9fe # v1.0.0

  lint:
    needs: pre-commit
    uses: darbiadev/.github/.github/workflows/python-lint.yaml@c4fb123ed14ed8cc9df9820ca63bace02981e9fe # v1.0.0

  test:
    needs: lint
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        python-version: [ "3.7", "3.8", "3.9", "3.10", "3.11", "3.12" ]

    uses: darbiadev/.github/.github/workflows/python-test.yaml@c4fb123ed14ed8cc9df9820ca63bace02981e9fe # v1.0.0
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
